mysite/blog/urls.py
from django.urls import path
from . import views
from . import models

#Template tagging
app_name = 'blog'

urlpatterns = [
    path('', views.PostList.as_view(template_name='index.html'), name='index'),
    path('contact/', views.contact, name='contact'),
    path('<slug:slug>/', views.post_detail, name='post_detail'),

    
]

mysite/mysite/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from blog import views


urlpatterns = [
    url(r'', views.home, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),
    
]

mysite/blog/models.py
from django.db import models
from django.contrib.auth.models import User


STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']

  

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

mysite/blog/forms.py
from .models import Comment
from django import forms
from django.forms import ModelForm



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'body')

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.views import generic
from django.views.generic import ListView,DetailView,CreateView,View
from .models import Post
from django.urls import reverse_lazy
from django.http import HttpResponse
from .forms import CommentForm
from django.core.mail import send_mail



class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'index.html'
    paginate_by = 3


def post_detail(request, slug):
    template_name = 'post_detail.html'
    post = get_object_or_404(Post, slug=slug)
    comments = post.comments.filter(active=True)
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():

            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, template_name, {'post': post,
                                           'comments': comments,
                                           'new_comment': new_comment,
                                           'comment_form': comment_form})




def contact(request):
    if request.method == 'POST':
        first_name = request.POST['first-name']
        email = request.POST['email']
        message = request.POST['message']

        # send an e-mail
        send_mail(
            first_name,#subject
            message,#message
            email,#from email
            ['ramazonqahhorov@gmail.com'],#to email


        )

        return render(request, 'contact1.html', {'first_name': first_name})    

    else:
        return render(request, 'contact1.html', {})    

mysite/mysite/views.py
#from django.shortcuts import render
#from blog.views import *
#from django.views.generic import TemplateView

mysite/templates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static "all.css" %}">
  <link rel="stylesheet" href="{% static "bootstrap.css" %}" >
  <link rel="stylesheet" href="{%static "style.css" %}">
  <link
      href="https://fonts.googleapis.com/css?family=Roboto:400,700"
      rel="stylesheet">

  <title>Online yuridik xizmatlar</title>
  <script src="//code.jivosite.com/widget/pvNOxCEa74" async></script>

   <style>


   </style>


</head>

<body>

  

  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container">
      <a href="{% url 'home' %}" class="navbar-brand"><img src="../static/assets/balogo.jpg" alt="" style=" width: 50px;">
        <strong style="color: aliceblue;">iLawyer.uz </strong></a>
      <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto"  style="font-family: 'Roboto', sans-serif; font-size: 14px;">
          <li class="nav-item">
            <a href="{% url 'home' %}" class="nav-link">Bosh sahifa</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'about' %}" class="nav-link">Biz haqimizda</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'blog:index' %}" class="nav-link">Blog</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'blog:contact' %}" class="nav-link">Biz bilan bog'laning</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>


  <div class="about-banner" style="background-color: #1e3c5f;">
    <div class="container text-center py-5 text-white">
      <h1 style="color: white ; ">Bizning kompaniyamiz haqida</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis aut doloribus dolores minus</br> voluptatibus in?</p>
    </div>
  </div>

  <div class="about-content">
    <div class="container">
      <div class="row py-5">
        <div class="col-md-6">
          <h3>What we do</h3>
          <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolorem, doloremque
            quidem quasi sint reiciendis rem voluptas atque ab nam non, qui excepturi unde optio cum,
            omnis necessitatibus recusandae a repellat.</p>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolorem, doloremque
              quidem quasi sint reiciendis rem voluptas atque ab nam non, qui excepturi unde optio cum,
              omnis necessitatibus recusandae a repellat.</p>

        </div>
        <div class="col-md-6">
          <img src="{% static 'assets/pexels-august-de-richelieu-4427430.jpg' %}" alt="" class="rounded-circle img-fluid about-img d-contents">

        </div>
      </div>
    </div>
  </div>

  <div class="our-staff" style="background-color: #1e3c5f;">
    <div class="container text-center text-white">
      <h2 style="color: white;">Bizning jamoa</h2>
      <div class="row">
        <div class="col-md-3">
          <img src="{% static 'assets/person1.jpg' %}" alt="" class="rounded-circle">
          <h3 style="color: white;">Lobar Hakimova</h3>
          <p>Lorem, ipsum dolor.</p>
        </div>
        <div class="col-md-3">
          <img src="{% static 'assets/person2.jpg' %}" alt=""class="rounded-circle">
          <h3 style="color: white;">Nigora Muxtorova</h3>
          <p>Lorem, ipsum dolor.</p>
        </div>
        <div class="col-md-3">
          <img src="{% static 'assets/person3.jpg' %}" alt=""class="rounded-circle">
          <h3 style="color: white;">Suxrob Murodov</h3>
          <p>Lorem, ipsum dolor.</p>
        </div>
        <div class="col-md-3">
          <img src="{% static 'assets/person4.jpg' %}" alt=""class="rounded-circle">
          <h3 style="color: white;">Farhod Shodmonov</h3>
          <p>Lorem, ipsum dolor.</p>
        </div>
      </div>
    </div>
  </div>

<!-- FOOTER -->
<footer id="main-footer" class="text-center p-4 bg-dark text-white">
  <div class="container">
    <div class="row">
      <div class="col">
        <p>Copyright &copy;
          <span id="year"></span> Kahharoff</p>
      </div>
    </div>
  </div>
</footer>


  <script src="{% static "jquery.js" %}"></script>
  <script src="{% static "popper.js" %}"></script>
  <script src="{% static "bootstrap.js" %}"></script>

  <script>
    // Get the current year for the copyright
    $('#year').text(new Date().getFullYear());

  </script>

<script>

  var preloader = document.getElementById('loader');

  function myFuncton(){
    preloader.style.display = 'none';
  }

</script>
</body>

</html>

mysite/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>

    <link
      href="https://fonts.googleapis.com/css?family=Roboto:400,700"
      rel="stylesheet">
    <meta name="google" content="notranslate" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />

  </head>

  <body>
    <style>
      body {
        font-family: "Roboto", sans-serif;
        font-size: 17px;
        background-color: lightblue;
      }

    /* .shadow{
           box-shadow: 0 4px 2px -2px rgba(0,0,0,0.1);
       } */
      .btn-danger {
        color: #fff;
        background-color:  #3361e0;
        border-color: #1e51dc;
      }

     .masthead {
              background:#1e3c5f;
              height: auto;
              padding-bottom: 15px;
              padding-top: 10px;
    }
    </style>

    <!-- Navigation -->
    


            {% block content %}
          <!-- Content Goes here -->
            {% endblock content %}

    <!-- Footer -->
    <footer class="py-3 bg-grey">
              <p class="m-0 text-dark text-center ">Copyright &copy; Kahharoff</p>
    </footer>

  </body>
</html>

mysite/templates/contact1.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>Biz bilan bog`laning</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static "contact/images/icons/favicon.ico" %}">
	<link rel="stylesheet" type="text/css" href="{% static "contact/vendor/bootstrap/css/bootstrap.min.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "contact/fonts/font-awesome-4.7.0/css/font-awesome.min.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "contact/fonts/Linearicons-Free-v1.0.0/icon-font.min.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "contact/vendor/animate/animate.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "contact/vendor/css-hamburgers/hamburgers.min.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "contact/vendor/animsition/css/animsition.min.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "contact/vendor/select2/select2.min.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "contact/vendor/daterangepicker/daterangepicker.css" %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "contact/css/util.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "contact/css/main.css" %}">
<!--===============================================================================================-->


</head>
<body >



	<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
		<div class="container">
		  <a href="{% url 'home' %}" class="navbar-brand">
			<img src="../static/assets/balogo.jpg" alt="">
			<strong style="color: aliceblue;">iLawyer.uz </strong>
		  </a>
		  <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
			<span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarCollapse">
			<ul class="navbar-nav ml-auto">
			  <li class="nav-item">
				<a href="{% url 'home' %}" class="nav-link">Bosh sahifa</a>
			  </li>
			  <li class="nav-item">
				<a href="{% url 'about' %}" class="nav-link">Biz haqimizda</a>
			  </li>
			  <li class="nav-item">
				<a href="{% url 'blog:index' %}" class="nav-link">Blog</a>
			  </li>
			  <li class="nav-item">
				<a href="{% url 'blog:contact' %}" class="nav-link">Biz bilan bog'laning</a>
			  </li>
			</ul>
		  </div>
		</div>
	  </nav>

	<center style="background-color: #1e3c5f; padding: 20px; color: white;">
		<h2>Rahmat {{ first_name }}!</h2>
		<p>Tez orada siz bilan bog`lanamiz!</p>
	</center> 
	<br/><br/><br/>
	<div class="container-contact100">
		<div class="wrap-contact100">
			<form action="{% url 'blog:contact' %}" method="POST" class="contact100-form validate-form">
				{% csrf_token %}
				<span class="contact100-form-title">
					Bizga xabar yuboring!
				</span>

				<label class="label-input100" for="first-name">Ismingiz</label>
				<div class="wrap-input100 rs1-wrap-input100 validate-input" data-validate="Type first name">
					<input id="first-name" class="input100" type="text" name="first-name" placeholder="First name">
					<span class="focus-input100"></span>
				</div>

				<label class="label-input100" for="email">Elektron Pochtangiz</label>
				<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
					<input id="email" class="input100" type="text" name="email" placeholder="Eg. example@email.com">
					<span class="focus-input100"></span>
				</div>

				<label class="label-input100" for="message">Xabar</label>
				<div class="wrap-input100 validate-input" data-validate = "Message is required">
					<textarea id="message" class="input100" name="message" placeholder="Write us a message"></textarea>
					<span class="focus-input100"></span>
				</div>

				<div class="container-contact100-form-btn">
					<button class="contact100-form-btn">
						Jo`natish
					</button>
				</div>
			</form>

			<div class="contact100-more flex-col-c-m" style="background-image: url('images/bg-01.jpg');"><!--url('images/bg-01.jpg')-->
				<div class="flex-w size1 p-b-47">
					<div class="txt1 p-r-25">
						<span class="lnr lnr-map-marker"></span>
					</div>

					<div class="flex-col size2">
						<span class="txt1 p-b-20">
							Manzil:
						</span>

						<span class="txt2">
							Ofiz manzili yeri
						</span>
					</div>
				</div>

				<div class="dis-flex size1 p-b-47">
					<div class="txt1 p-r-25">
						<span class="lnr lnr-phone-handset"></span>
					</div>

					<div class="flex-col size2">
						<span class="txt1 p-b-20">
							Qo`ngiroq uchun
						</span>

						<span class="txt3">
							+1 800 1236879
						</span>
					</div>
				</div>

				<div class="dis-flex size1 p-b-47">
					<div class="txt1 p-r-25">
						<span class="lnr lnr-envelope"></span>
					</div>

					<div class="flex-col size2">
						<span class="txt1 p-b-20">
							Umumiy savollar uchun
						</span>

						<span class="txt3">
							contact@example.com
						</span>
					</div>
				</div>
			</div>
		</div>
	</div>



	<div id="dropDownSelect1"></div>

	<!--=======================================================================Preloader-->
	
	<!--=======================================================================Preloader-->

<!--===============================================================================================-->
	<script src="{% static "contact/vendor/jquery/jquery-3.2.1.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "contact/vendor/animsition/js/animsition.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "contact/vendor/bootstrap/js/popper.js" %}"></script>
	<script src="{% static "contact/vendor/bootstrap/js/bootstrap.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "contact/vendor/select2/select2.min.js" %}"></script>
	<script>
		$(".selection-2").select2({
			minimumResultsForSearch: 20,
			dropdownParent: $('#dropDownSelect1')
		});
	</script>
<!--===============================================================================================-->
	<script src="{% static "contact/vendor/daterangepicker/moment.min.js" %}"></script>
	<script src="{% static "contact/vendor/daterangepicker/daterangepicker.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "contact/vendor/countdowntime/countdowntime.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "contact/js/main.js" %}"></script>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-23581568-13');
	</script>

</body>
</html>

mysite/templates/index.html
{% extends "base.html" %}

 {% block content %}
 <script src="//code.jivosite.com/widget/pvNOxCEa74" async></script>
<style>

    body {
        font-family: "Roboto", sans-serif;
        font-size: 14px;
        background-color: #ffffff;
        background-image: url('../static/assets/4d784638e3c95a9660755f302ae01e41.jpg');
    }

    .head_text{
    color: white;
  }
  .card-body {
    background-color: gainsboro;
  }
  .card-title {
    text-align: center;
    font-family: fantasy;
  }
    

</style>
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container">
      <a href="{% url 'home' %}" class="navbar-brand">
        <img src="../static/assets/balogo.jpg" alt="" style=" width: 50px;">
        <strong style="color: aliceblue;">iLawyer.uz </strong>
      </a>
      <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a href="{% url 'home' %}" class="nav-link">Bosh sahifa</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'about' %}" class="nav-link">Biz haqimizda</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'blog:index' %}" class="nav-link">Blog</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'blog:contact' %}" class="nav-link">Biz bilan bog'laning</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

    <header class="masthead" >
            <div class="overlay"></div>
            <div class="container">
              <div class="row">
                <div class=" col-md-8 col-md-10 mx-auto">
                  <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white" style="text-align: center; font-size: 35px;">Post bo`limi </h3>
                    <p class="text-light" style="text-align: center;">Post haqida toliq malumot
                    </p>
                  </div>
                      </div>
                    </div>
                  </div>
              
              </header>

            <div class="container">
                <div class="row">

              <!-- Blog Entries Column -->
              <div class="col-md-8 mt-3 left">
                    {% for post in post_list %}
                <div class="card mb-4" >
                  <div class="card-header" style="background-color: lightblue;">
                    <h2 class="card-title">{{ post.title }}</h2>
                  </div>
                  <div class="card-body">
                    <!-- <h2 class="card-title">{{ post.title }}</h2>
                    <hr> -->
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>

                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <div class="text-center">
                       <a href="{% url 'blog:post_detail' post.slug  %}" class="btn btn-primary">Batafsil &rarr;</a>
                    </div>
                   
                  </div>

                </div>
                {% endfor %}
            </div>
                {% block sidebar %}
                {% include 'sidebar.html' %}
                {% endblock sidebar %}
            </div>
        </div>
        {% if is_paginated %}
          <nav aria-label="Page navigation conatiner">
            <ul class="pagination justify-content-center" >
              {% if page_obj.has_previous %}
              <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; Oldingi </a></li>
              {% endif %}
              {% if page_obj.has_next %}
              <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> Keyingi &raquo;</a></li>

              {% endif %}
            </ul>
          </nav>
        {% endif %}
{%endblock%}

mysite/templates/post_detail.html
{% extends 'base.html' %} {% block content %}
{% load static %}
{% load crispy_forms_tags %}
<script src="//code.jivosite.com/widget/pvNOxCEa74" async></script>
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
    <a href="{% url 'home' %}" class="navbar-brand">
      <img src="../static/assets/balogo.jpg" alt="" style=" width: 50px;">
        <strong style="color: aliceblue;">iLawyer.uz </strong> 
    </a>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav ml-auto" style="font-size: 14px;">
        <li class="nav-item">
          <a href="{% url 'home' %}" class="nav-link">Bosh sahifa</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'about' %}" class="nav-link">Biz haqimizda</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'blog:index' %}" class="nav-link">Blog</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'blog:contact' %}" class="nav-link">Biz bilan bog'laning</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1 style="text-align: center; font-size: 35px; font-family: fantasy;">{% block title %} {{ post.title }} {% endblock title %}</h1>
        <hr>
        <p class=" text-muted" style="font-family: monospace;">{{ post.author }} | {{ post.created_on }}</p>
        <p class="card-text ">{{ post.content | safe }}</p>
      </div>
    </div>
    {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}

    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        <!-- comments -->
        <h2 style="text-align: center; font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;">{{ comments.count }} ta Izohlar</h2>
        <hr>
        {% for comment in comments %}
        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            {{ comment.name }}
            <span class=" text-muted font-weight-normal">
              {{ comment.created_on }}
            </span>
          </p>
          {{ comment.body | linebreaks }}
          <hr style="background-color: black;">
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="col-md-8 card mb-4  mt-3 " style="background-color: lightsteelblue;">
      <div class="card-body" >
        {% if new_comment %}
        <div class="alert alert-success" role="alert">
          Izohingiz qabul qilindi tez orada javob olasiz...
        </div>
        {% else %}
        <h3 style="text-align: center; font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;">Izohingizni qoldiring</h3>
        <form method="post" style="margin-top: 1.3em;">
          {{ comment_form | crispy }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary  btn-lg">Izohni jo`natish</button>
        </form>
        {% endif %}
      </div>
    </div>
  </div>
</div>


{% endblock content %}

mysite/templates/sidebar.html
{% block sidebar %}

<style>
       

</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card my-4" style="background-color: lightblue;">
        <h5 class="card-header" style="text-align: center; font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;">Biz Haqimizda!</h5>
    <div class="card-body" style="background-color: lightgray;">
        <p class="card-text"> Ko`rsatiladigan barcha xizmatlar bilimli va tajribali mutaxasislar tomonidan beriladi</p>
        <a href="{% url 'about' %}"
           class="btn btn-primary">Ko`proq</a>
    </div>
</div>
</div>

{% endblock sidebar %}